[package]
name = "nym-macos"
description = "Abstractions for macOS"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[target.'cfg(target_os="macos")'.dependencies]
libc = "0.2"
tracing = { workspace = true }
