name: build-winfw-windows
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      CPP_BUILD_MODES:
        value: ${{ jobs.build.outputs.CPP_BUILD_MODES }}

env:
  CARGO_TERM_COLOR: always
  CPP_BUILD_MODES: Release

# https://github.com/actions/runner-images/issues/1794#issuecomment-707217728

jobs:
  build:
    runs-on: "custom-windows-11"
    outputs:
      CPP_BUILD_MODES: ${{ env.CPP_BUILD_MODES }}

    steps:
      - name: Cleanup working directory
        shell: bash
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # This step is prone to compiler error that are simply blanks, this action auto retries a few times in case of error
      - name: Build/Move winfw
        uses: nick-fields/retry@v3
        with:
          shell: pwsh
          timeout_seconds: 300
          max_attempts: 3
          retry_on: error
          command: |
            .\build-windows-modules.ps1 -BuildConfiguration ${{ env.CPP_BUILD_MODES }} -Platform x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winfw.dll
          path: |
            ${{ github.workspace }}/nym-vpn-windows/winfw/bin/x64-${{ env.CPP_BUILD_MODES }}/winfw.dll
          retention-days: 10

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winfw.lib
          path: |
            ${{ github.workspace }}/nym-vpn-windows/winfw/bin/x64-${{ env.CPP_BUILD_MODES }}/winfw.lib
          retention-days: 10
