name: crowdin-windows-linux-upload

on:
  push:
    branches:
      - develop
    paths: "nym-vpn-app/src/i18n/en/**"
  workflow_dispatch:

jobs:
  crowdin-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: false
          config: "crowdin-configs/linux-windows.yml"
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}