name: crowdin-windows-linux-download

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  crowdin-download:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push changes
      pull-requests: write  # Required to create PRs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          config: "crowdin-configs/linux-windows.yml"
          localization_branch_name: l10n_crowdin_windows_linux_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Windows & Linux Translations'
          pull_request_body: 'New Crowdin Windows & Linux translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}